version: '3.8'  
  
services:  
  frontend:  
    build:  
      context: .  
      dockerfile: Dockerfile.frontend  
      args:
        REACT_APP_MODE: prod
    ports:  
      - "3080:80"  
    depends_on:  
      - backend
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - chroma
    ports:
      - "8080:8000"
    environment:
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000

  chroma:
    build:
      context: ./backend
      dockerfile: Dockerfile.chroma
    volumes:
      - "./backend/chroma_store:/data"
    ports:
      - "8002:8000"